#!/bin/sh

#
# brewedperlrebase - rebase for brewed perl (perlrebase for perlbrew)
#
# Copyright (c) 2011 Yu-ji Hosokawa
# This program is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#


PATH=/bin
baseaddr=0x57000000
filelist=/tmp/brewedperlrebase.$$
noact=

usage ()
{
    self=`basename $0`
    echo "usage: $self [-t BREWED_PERL_TARGET] [-b BASE_ADDRESS] [-v] [-n]"
    exit 1
}


cleanup ()
{
    rm -f $filelist
}


while getopts t:b:vn opt "$@"
do
    case $opt in
        t )
            brew=$OPTARG;;
        b )
	    baseaddr=$OPTARG;;
        v )
            verbose=-v;;
        n )
            noact=1;;
        * )
	    usage
            exit;;
    esac
done

if [ -z $brew ]; then
    #PATH=/bin:$PERLBREW_PATH
    #brew=$( perlbrew list | perl -nale 'print $F[1] if m{\A\* (?!/)}' )
    brew=$PERLBREW_PERL
fi
if [ -z $brew ]; then
    echo "no brewed perl target specified."
    usage
    exit
fi
if [ ! -d $PERLBREW_ROOT/perls/$brew ]; then
    echo "brewed perl target not found:" $brew
    usage
    exit
fi

echo "target: $brew"

trap cleanup 1 2 3 15
find $PERLBREW_ROOT/perls/$brew -name perl\*.exe -o -name \*.dll > $filelist
if [ -z $noact ]; then
    cat $filelist | xargs chmod u+w
    rebase $verbose -b $baseaddr -T $filelist
    cat $filelist | grep \.dll | peflags $verbose -d0 -T -
else
    cat $filelist
fi
cleanup
