=pod

=head1 NAME

brewedperlrebase - rebase for perlbrew Perl on Cygwin


=head1 SYNOPSIS

 brewedperlrebase [-t BREWED_PERL_TARGET] [-b BASE_ADDRESS] [-v] [-n]
  -t  specify the perlbrew Perl
  -b  base address
  -v  verbose output
  -n  Do not perform rebase.  Only the filename to be rebased is display

You probably don't need to specify options.

 $ brewedperlrebase

rebases the perl binaries, which is used for current shell with perlbrew.
Equivalent to C<brewedperlrebase -t $PERLBREW_PERL>.


 $ brewedperlrebase -t perl-5.10.1 -n

shows a list of file which is to be rebased.


=head1 DESCRIPTION

C<brewedperlrebase> is a shell script which rebases C<perlbrew> Perl
installation to make C<fork()> function properly.

This is a implementation of the C<perlrebase> for C<perlbrew> Perl.
For the Perl from Cygwin distribution package or /usr/local installation,
you can use C<perlrebase> instead.


=head1 DEPENDENCIES

bash, coreutils, findutils, perl, perlbrew


=head1 SEE ALSO

F</usr/share/doc/Cygwin/rebase-3.0.1.README>,
rebase(1), rebaseall(1), perlrebase(1).


=head1 AUTHOR

Yu-ji Hosokawa <L<http://u.hoso.net/>>, <L<https://github.com/yunh>>


=head1 COPYRIGHT

Copyright (c) 2011 Yu-ji Hosokawa


=head1 LICENCE

This program is free software; you can redistribute it and/or
modify it under the same terms as Perl itself.


=cut
